name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:
      # 1) CHECKOUT DO REPO
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) CONFIGURAR CREDENCIAIS AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3) LOGIN NO ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 4) BUILD E PUSH DA IMAGEM
      - name: Build, Tag and Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: iscoolgpt-backend
          IMAGE_TAG: latest
        run: |
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # 5) RENDER TASK DEFINITION COM IMAGEM e ENV
      - name: Render ECS task definition with image and env
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task.json
          container-name: iscoolgpt
          image: ${{ steps.login-ecr.outputs.registry }}/iscoolgpt-backend:latest
          environment-variables: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}

      # 6) DEPLOY NO ECS
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task.json
          cluster: iscoolgpt-cluster
          service: iscoolgpt-task-service
          wait-for-service-stability: true